version: "3"

services:

  database:
    image: lucas10sh/databasejava
    build: "./database"
    #image: my-mysql
    ports:
      - "3306:3306"
    restart: always
    #command: --default-authentication-pllugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: app123
      MYSQL_DATABASE: catalog1
  app:
    #banco de dados precisa iniciar para o app rodar
    image: lucas10sh/javaapi
    build: "./consultoria"
    depends_on:
      - database
    ports:
      - "5041:8080"
    container_name: spring_container
    restart: always

    environment:
      DBHOST: database
      DATABASE_NAME: catalog1
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: app123
